const express = require("express")
const cors = require("cors")
const axios = require("axios")
require("dotenv").config()

const app = express()

app.use(cors())
app.use(express.json())

app.get("/", (req, res) => {
res.send("Server is running")
})

app.post("/chat", async (req, res) => {
const message = req.body.message.toLowerCase()

// 🔥 Try REAL AI first
try {

const response = await axios.post(
"https://openrouter.ai/api/v1/chat/completions",
{
model: "mistralai/mistral-7b-instruct",
messages: [
{ role: "user", content: message }
]
},
{
headers: {
"Authorization": `Bearer ${process.env.OPENROUTER_API_KEY}`,
"Content-Type": "application/json",
"HTTP-Referer": "http://localhost:3000",
"X-Title": "AI Study Agent"
}
}
)

const reply = response.data.choices[0].message.content

return res.json({ reply })

} catch (error) {

console.log("AI FAILED → using fallback")

// 🔥 SMART FALLBACK (never fails)
let reply = ""

if (message.includes("laplace")) {
reply = "Laplace Transform converts a signal from time domain to frequency domain, making differential equations easier to solve."
}
else if (message.includes("fourier")) {
reply = "Fourier Transform breaks signals into frequency components."
}
else if (message.includes("os") || message.includes("operating system")) {
reply = "An Operating System manages hardware and software resources and acts as an interface between user and system."
}
else if (message.includes("ai")) {
reply = "Artificial Intelligence enables machines to simulate human intelligence like learning and decision making."
}
else if (message.includes("algorithm")) {
reply = "An algorithm is a step-by-step procedure used to solve a problem."
}
else {
reply = "This is an AI-style response generated by fallback system when real AI is unavailable."
}

return res.json({ reply })
}
})

app.listen(3000, () => {
console.log("Server running on port 3000")
})

// keep alive
setInterval(() => {}, 1000)