const express = require("express")
const cors = require("cors")

const app = express()

app.use(cors())
app.use(express.json())

app.get("/", (req, res) => {
res.send("Server is running")
})

app.post("/chat", (req, res) => {

const authHeader = req.headers.authorization

if (!authHeader) {
return res.json({ reply: "❌ Please login first" })
}

const token = authHeader.split(" ")[1]

if (!token) {
return res.json({ reply: "❌ Invalid token" })
}

const message = req.body.message.toLowerCase()

// 🔥 Smart AI-like responses
let reply = ""

if (message.includes("laplace")) {
reply = "Laplace Transform converts signals from time domain into frequency domain, making complex differential equations easier to solve."
}
else if (message.includes("fourier")) {
reply = "Fourier Transform breaks a signal into its individual frequency components."
}
else if (message.includes("os") || message.includes("operating system")) {
reply = "An Operating System manages hardware resources and provides an interface for users and applications."
}
else if (message.includes("ai")) {
reply = "Artificial Intelligence enables machines to mimic human intelligence like learning and decision making."
}
else {
reply = "This is a smart AI-style response generated by the system."
}

res.json({ reply })
})

app.listen(3000, () => {
console.log("Server running on port 3000")
})